# Generated by Django 5.2.6 on 2025-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='model_version',
            field=models.CharField(default='distilbert_v1', max_length=256),
        ),
    ]
